---
title: "ggalluvial_walkthrough"
author: "Yifei Liu"
date: "7/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


load packages
```{r}
library(tidyverse)
library(ggalluvial)
library(ggfittext)
theme_set(theme_minimal())

```





```{r}
head(as.data.frame(UCBAdmissions), n = 12)

is_alluvia_form(as_tibble(UCBAdmissions), axes = 1:3, silent = T)



```



```{r}
as.data.frame(UCBAdmissions) %>%
  ggplot(aes(y = Freq, axis1 = Gender, axis2 = Dept)) +
  geom_alluvium(aes(fill = Admit), width = 1/12) +
  geom_stratum(width = 1/12, fill = "black", color = "grey") +
  geom_label(stat = "stratum", label.strata = TRUE) +
  scale_x_discrete(limits = c("Gender", "Dept"), expand = c(.05, .05)) +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  labs(title = "UC Berkeley admissions and rejection, by sex and department")




```


```{r}
as.data.frame(Titanic) %>%
  ggplot(aes(y = Freq, 
             axis1 = Survived, axis2 = Sex, axis3 = Class)) +
  geom_alluvium(aes(fill = Survived),
                width = 0, knot.pos = 0, reverse = F) +
  geom_stratum(width = 1/8, reverse = F) +
  geom_text(stat = "stratum", label.strata = T, reverse = F) +
  scale_x_continuous(breaks = 1:3, labels = c("Survived", "Sex", "Class")) +
  coord_flip() +
  labs(title = "Titanic survival by class and sex") +
  theme(legend.position = "bottom",
        plot.title = element_text(face = "bold", hjust = 0.5),
        panel.grid = element_blank())


```


### Lodes (long) format

```{r}
UCB_lodes <- to_lodes_form(as.data.frame(UCBAdmissions),
                           axes = 1:3, 
                           id = "Cohort")

is_lodes_form(UCB_lodes,key = x, value = stratum, id = Cohort, silent = T)
```



```{r}
data(Refugees, package = "alluvial")

country_regions <- c(
  Afghanistan = "Middle East",
  Burundi = "Central Africa",
  `Congo DRC` = "Central Africa",
  Iraq = "Middle East",
  Myanmar = "Southeast Asia",
  Palestine = "Middle East",
  Somalia = "Horn of Africa",
  Sudan = "Central Africa",
  Syria = "Middle East",
  Vietnam = "Southeast Asia"
)

Refugees$region <- country_regions[Refugees$country]

is_alluvia_form(Refugees, axes = c(1,2,4), silent = T)

ggplot(data = Refugees, 
       aes(x = year, y = refugees, alluvium = country)) +
  geom_alluvium(aes(fill = country, colour = country),
                alpha = 0.75, decreasing = F) +
  scale_x_continuous(breaks = seq(2003, 2013, 2)) +
  scale_fill_brewer(type = "qual", palette = "Set3") +
  scale_color_brewer(type = "qual", palette = "Set3") +
  facet_wrap(~ region, scales = "fixed")+
  labs(x = "", y = "# Refugees",
       title = "Refugges volume by country and regio of origin") +
  theme(legend.position = "bottom",
        plot.title = element_text(face = "bold", hjust = 0.5),
        panel.grid = element_blank())


ggplot(Refugees, aes(x = year, y = refugees, alluvium = country)) +
  geom_alluvium(aes(fill = country, colour = country),
                alpha = 0.75, decreasing = F) +
  scale_color_brewer(type = "qual", palette = "Set2") +
  scale_fill_brewer(type = "qual", palette = "Set2") +
  facet_wrap(~ region, scales = "fixed")

```



```{r}

data("majors")

majors %>%
  mutate(curriculum = as.factor(curriculum)) %>%
  ggplot(aes(semester, stratum = curriculum, alluvium = student,
             fill = curriculum, label = curriculum)) +
  scale_fill_brewer(type = "qual", palette = "Set2") +
  geom_flow(stat = "alluvium", lode.guidance = "rightleft",
            color = "darkgray") +
  geom_stratum() +
  labs(title = "Student curricula across several semesters") +
  theme(legend.position = "bottom",
        panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5, face = "bold"))



```



```{r}
data(vaccinations)
levels(vaccinations$response) <- rev(levels(vaccinations$response))
ggplot(vaccinations,
       aes(x = survey, stratum = response, alluvium = subject,
           y = freq,
           fill = response, label = response)) +
  scale_x_discrete(expand = c(.1, .1)) +
  geom_flow() +
  geom_stratum(alpha = .5) +
  geom_text(stat = "stratum", size = 3) +
  theme(legend.position = "none") +
  ggtitle("vaccination survey responses at three points in time")

```

### Label small strata

```{r}

data("vaccinations")

ggplot(vaccinations,
       aes(x = survey, stratum = response, alluvium = subject, y = freq,
           fill = response, label = response)) +
  scale_x_discrete(expand = c(.1, 0)) +
  geom_flow(width = 1/4) +
  geom_stratum(alpha = .5, width = 1/4) +
  geom_text(stat = "stratum", size = 4) +
  theme(legend.position = "none") +
  ggtitle("vaccination survey responses", "labeled using `geom_text()`")

```

```{r}
ggplot(vaccinations,
       aes(x = survey, stratum = response, alluvium = subject, y = freq,
           fill = response, label = response)) +
  scale_x_discrete(expand = c(0.1, 0)) +
  geom_flow(width = 1/4) +
  geom_stratum(alpha = 0.5, width = 1/4) +
  geom_fit_text(stat = "stratum", width = 1/4, min.size = 3) +
  labs(title = "Vaccination survey responses",
       subtitle = "labeled using 'geom_fit_text()'") +
  theme(legend.position = "bottom",
        panel.grid = element_blank()) 


```


















