---
title: "Highchart walkthrough"
author: "Yifei Liu"
date: "4/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(highcharter)
library(ggplot2)
library(viridis)
```

```{r}
glimpse(pokemon)
```

```{r}
pokemon %>%
  count(type_1) %>%
  arrange(-n) %>%
  hchart(type = "bar",
         hcaes(x = type_1, y = n)) %>%
  hc_title(text = "Highchart Rule")

```

```{r}
pokemon %>%
  count(type_1) %>%
  arrange(-n) %>%
  hchart(type = "treemap",
         hcaes(x = type_1, value = n, color = n)) %>%
  hc_title(text = "Highchart Rule")
```

```{r}
pokemon %>%
  count(type_1) %>%
  arrange(-n) %>%
  hchart(type = "column",
         hcaes(x = type_1, y = n)) %>%
  hc_title(text = "Highchart Rule")

```
```{r}

highchart() %>%
  hc_add_series(pokemon, "scatter", hcaes(x = height, y = weight))

```

```{r}
diamond_sample <- sample_n(diamonds, 300)

modles <- loess(price ~ carat, data = diamond_sample)
fit <- arrange(augment(modles), carat)

highchart() %>%
  hc_add_series(diamond_sample, type = "scatter",
                hcaes(x = carat, y = price, size = depth, group = cut)) %>%
  hc_add_series(fit, type = "line", 
                hcaes(x = carat, y = .fitted), name = "Fit", id = "fit") %>%
  hc_add_series(fit, type = "arearange",
                hcaes(x = carat, low = .fitted - 2*.se.fit,
                      high = .fitted + 2 *.se.fit), linkedTo = "fit")

```

```{r}
pokemon %>%
  mutate(type_2 = ifelse(is.na(type_2), paste("Only", "type_1"), type_2),
         type_1 = type_1) %>%
  group_by()

```



```{r}
data("vaccines")

hchart(vaccines, "heatmap", hcaes(x = year, y = state, value = count)) %>% 
  hc_colorAxis(stops = color_stops(10, rev(inferno(10))),
               type = "logarithmic") %>% 
  hc_yAxis(reversed = TRUE, offset = -20, tickLength = 0,
           gridLineWidth = 0, minorGridLineWidth = 0,
           labels = list(style = list(fontSize = "8px")))
```

```{r}
series = list(
  list(
    data = c(29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4),
    name = 'Hola linear',
    color = 'red'
  ),
  list(
    data = c(54.4, 95.6, 194.1, 216.4, 148.5, 135.6, 176, 144, 129.2, 106.4, 71.5, 29.9),
    name = "Reverse!",
    color = 'green'
  )
)

highchart() %>%
  hc_add_series_list(series)


```

```{r}
labels = list(align = "left",
              style = list(
                fontSize = "16px",
                fontWeight = "bold",
                color = "blue"
              ))

highchart() %>%
  hc_add_series_list(series) %>%
  hc_xAxis(min = 1,
         max = 7,
         lineWith = 5, 
         labels = labels)


```

```{r}
data("citytemp")

highchart() %>%
  hc_xAxis(categories = citytemp$month) %>%
  hc_add_series(name = "Tokyp", data = citytemp$tokyo) %>%
  hc_add_series(name = "London", data = citytemp$london)

```

```{r}
x <- citytemp %>%
  gather(key = city, value = temp, tokyo:london) %>%
  hchart(type = "line",
         hcaes(y = temp, group = city, x = month))

glimpse(x)

```


```{r}
x$x$hc_opts$series[[1]][["name"]]


```

```{r}

```








Ref: https://www.datacamp.com/community/tutorials/data-visualization-highcharter-r
https://dantonnoriega.github.io/ultinomics.org/post/2017-04-05-highcharter-explainer.html


