---
title: "plotly 3D plot"
author: "Yifei Liu"
date: "1/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(plotly)
library(tidyverse)

```

$$f(x+\Delta x, y + \Delta y) = e^{-(x^2 + y^2)}$$


```{r}

data_3d = tibble(
  x = seq(-2, 2, by = 0.1),
  y = seq(-2, 2, by = 0.1),
  z = exp(-(x^2 + y^2))
)

matrix_3d = as.matrix(data_3d$z, ncol = nrow(data_3d))
rownames(matrix_3d) = data_3d$x
rownames(matrix_3d) = data_3d$y

p <- plot_ly(z = ~matrix_3d) %>% add_surface()

p

```


```{r}

# volcano is a numeric matrix that ships with R
p <- plot_ly(z = ~volcano) %>% add_surface(
  contours = list(
    z = list(
      show=TRUE,
      usecolormap=TRUE,
      highlightcolor="#ff0000",
      project=list(z=TRUE)
      )
    )
  ) %>%
  layout(
    scene = list(
      camera=list(
        eye = list(x=1.87, y=0.88, z=-0.64)
        )
      )
  )

p

```

3d plot a function to visualzied gradient descent

$$f(x, y) = x^2y$$

```{r}

x1 = seq(-4, 4, by = 0.1)
y1 = seq(-4, 4, by = 0.1)
z = x1^2 * y1

freqz <- with(data.frame(x1,y1), MASS::kde2d(x1, y1, n = 50))
with(freqz, plot_ly(x = x1, y = y1, z = z, type = "surface")) 


plot_ly(x = x1, y = y1, z = z, type = "surface")
```











