---
title: "Foilage animation"
author: "Yifei Liu"
date: "10/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rprojroot)
library(sf)
library(magick)
library(tidyverse)
library(gganimate)
library(transformr) # devtools::install_github("thomasp85/transformr")
detach("package:dplyr", unload = TRUE)
library(dplyr)
library(lubridate)
library(adehabitatHR)  #for generating spatial objects (note, this includes the pacakge sp)
library(gganimate)  #for animating our ggplots
library(ggspatial) #for adding important map elements (like scales and compasses) to our ggplots
library(viridis)

```


```{r}
root <- "/Users/yifeiliu/Documents/R/data/EDA/Blog_draft"

c("https://s3.amazonaws.com/smc0m-tech-stor/static/js/us.min.json",
  "https://smokymountains.com/wp-content/themes/smcom-2017/js/foliage2.tsv",
  "https://cdn.smokymountains.com/static/maps/rendered.csv") %>%
  walk(~{
    sav_tmp <- file.path(root, basename(.x))
    if (!file.exists(sav_tmp)) download.file(.x, sav_tmp)
  })

states_sf <- read_sf(file.path(root, "us.min.json"), "states", stringsAsFactors = FALSE)

# only save continental US
states_sf <- filter(states_sf, !(id %in% c("2", "15", "72", "78")))

# it doesn't have a CRS so we give it one
st_crs(states_sf) <- 4326

# I ran into hiccups using coord_sf() to do this, so we convert it to Albers here
states_sf <- st_transform(states_sf, 5070)

# next we read in the states
counties_sf <- read_sf(file.path(root, "us.min.json"), "counties", stringsAsFactors = FALSE)
st_crs(counties_sf) <- 4326
counties_sf <- st_transform(counties_sf, 5070)

# now, we read in the foliage data
foliage <- read_csv(
  file.path(root, "rendered.csv"),
  na = "#N/A",
  col_types = cols(.default=col_double(), id=col_character())
)

colnames(foliage) <- c("id", sprintf("rate%d", 1:13))

# and, since we have a lovely sf tidy data frame, bind it together
foliage_sf <- left_join(counties_sf, foliage, "id") %>%
  filter(!is.na(rate1)) 

# now, we do some munging so we have better labels and so we can
# iterate over the weeks

foliage_sf <- foliage_sf %>%
  gather(week, value, -id, -geometry) %>%
  mutate(value = factor(value)) %>%
  filter(week != "rate1") %>%
  mutate(week = factor(week,
                       levels=unique(week),
                       labels=format(seq(as.Date("2019-09-08"),
                                         as.Date("2019-11-30"), "1 week"),
                                     "%b %d")),
         week = paste0(week, " 2019"),
         week = mdy(week))
```

now anime this chart

```{r}
ggplot() +
  geom_sf(data = foliage_sf, aes(fill = value), size = 0.05, color = "#2b2b2b") +
  geom_sf(data=states_sf, color="white", size=0.25, fill=NA) +
  viridis::scale_fill_viridis(
      name=NULL,
      option = "magma",
      direction = -1,
      discrete = TRUE,
      labels=c("No Change", "Minimal", "Patchy", "Partial", "Near Peak", "Peak", "Past Peak"),
      drop=FALSE
    ) +
  labs(title = 'Foilage: {frame_time}') +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 24)) +
  coord_sf(datum = NA) +
  labs(title = 'Date: {current_frame}') +
  transition_manual(week) 
  


```











