---
title: "Federal Research and Development Spending by Agency"
author: "Yifei Liu"
date: "2/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
detach("package:dplyr", unload=TRUE)
library(dplyr)
library(rjson)
library(scales)
library(streamgraph)

theme_set(theme_minimal())

fed_rd <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-12/fed_r_d_spending.csv")

energy_spend <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-12/energy_spending.csv")

climate_spend <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-12/climate_spending.csv")

options(digits = 3)

```

see how those number trend


```{r}
# view us gdp, inflation adjusted

fed_rd %>% 
  ggplot(aes(year, gdp)) +
  geom_line() +
  expand_limits(y = 0) +
  scale_y_continuous(labels = dollar_format(prefix = "T$", scale = 0.000000000001))

# view total budge , inflation adjusted
fed_rd %>%
  ggplot(aes(year, total_outlays)) +
  geom_line() +
  expand_limits(y = 0) +
  scale_y_continuous(labels = dollar_format(prefix = "B$", scale = 0.000000001))

# View different agency and department spending trend
streamgraph(fed_rd, key = "department", value = "rd_budget", date = "year", offset = "expand") %>%
  sg_axis_x(2, "year", "%Y") %>%
  sg_fill_tableau("cyclic") %>%
  sg_legend(show = F, label = "Federal Agency Budget:")

fed_rd %>%
  mutate(percent = rd_budget / total_outlays) %>%
  ggplot(aes(year, percent, fill = department)) +
  geom_area() +
  scale_y_continuous(labels = percent_format())

# 

federal_pct <- fed_rd %>%
  mutate(percent = rd_budget / total_outlays) 

federal_pct %>%
  streamgraph(key = "department", value = "percent", date = "year", offset = "zero", interpolate = "step") %>%
  sg_legend(show = T, label = "Name:")

```



```{r}

energy_spend %>% 
  group_by(year) %>%
  summarize(sum = sum(energy_spending)) %>%
  inner_join(energy_spend, by = "year")


coul <- colorRampPalette(brewer.pal(11, "BuPu"))(11)


energy_spend %>%
  group_by(year) %>%
  add_tally(wt = energy_spending) %>%
  mutate(pct = energy_spending / n) %>%
  ggplot(aes(year, pct, fill = department)) +
  geom_col() +
  scale_fill_manual(values = coul) +
  scale_y_continuous(labels = percent_format()) +
  labs(x = "", y = "", fill = "Energy Department",
       title = "Which Energy department spend the most? %",
       subtitle = "Data Source: Federal Research and Development Spending by Agency @yifei_liu") +
  theme(plot.subtitle = element_text(face = "italic", size = 8, hjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank())
  

  
energy_spend %>%
  group_by(year) %>%
  ggplot(aes(year, energy_spending, fill = department)) +
  geom_col() +
  scale_fill_manual(values = coul) +
  scale_y_continuous(labels = dollar_format(scale = 0.000001, suffix = "B$", prefix = "")) +
  labs(x = "", y = "", fill = "Energy Department",
       title = "Which Energy department spend the most? $",
       subtitle = "Data Source: Federal Research and Development Spending by Agency @yifei_liu") +
  theme(plot.subtitle = element_text(face = "italic", size = 8, hjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank())





```

## Global Climate Change Research Program spending

```{r}

coul <- colorRampPalette(brewer.pal(11, "Greens"))(11)

climate_spend %>%
  group_by(year) %>%
  add_tally(wt = gcc_spending) %>%
  mutate(pct = gcc_spending / n) %>%
  ggplot(aes(year, pct, fill = department)) +
  geom_col() +
  scale_fill_manual(values = coul) +
  scale_y_continuous(labels = percent_format()) +
  labs(x = "", y = "", fill = "Sub-agency of Gobal Climate Change Spending",
       title = "Which Department spend the most amount of money on Global Climate Change? %",
       subtitle = "Data Source: Federal Research and Development Spending by Agency @yifei_liu") +
  theme(plot.subtitle = element_text(face = "italic", size = 8, hjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank())

climate_spend %>%
  group_by(year) %>%
  ggplot(aes(year, gcc_spending, fill = department)) +
  geom_col() +
  scale_fill_manual(values = coul) +
  scale_y_continuous(labels = dollar_format(scale = 0.000001, suffix = "B$", prefix = "")) +
  labs(x = "", y = "", fill = "Sub-agency of Gobal Climate Change Spending",
       title = "Which Department spend the most amount of money on Global Climate Change? $",
       subtitle = "Data Source: Federal Research and Development Spending by Agency @yifei_liu") +
  theme(plot.subtitle = element_text(face = "italic", size = 8, hjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank())



```







