---
title: "Analyzing US dairy consumption"
author: "Yifei Liu"
date: "1/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
detach("package:dplyr", unload=TRUE)
library(dplyr)
library(sweep)
library(forecast)
library(tidyquant)
library(lubridate)
library(scales)
library(timetk)
theme_set(theme_minimal())


milk_product_facts <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/milk_products_facts.csv")



```


```{r}

 milk_products_tidies <- milk_product_facts %>% 
  gather(product, lbs_per_person, - year) %>%
  separate(product, c("category", "product"), sep = "_", extra = "merge",
           fill = "right") %>%
   mutate(product = coalesce(product, category),
          product = str_to_title(str_replace_all(product, "_", " ")),
          category = str_to_title(category),
          product = ifelse(product == "Other", paste(product, category), product))
   

milk_products_tidies %>%
  group_by(category, year) %>%
  summarize(lbs_per_person = sum(lbs_per_person)) %>%
  ggplot(aes(year, lbs_per_person, color = category)) +
  geom_line() +
  labs(x = "Year",
       y = "Lbs Per Person",
       title = "Dairy consumption by category",
       subtitle = "base on US consumption (source:USDA)")

# we can see milk distorted the scale

milk_products_tidies %>%
  group_by(product = fct_lump(product, 6, w = lbs_per_person),
         year) %>%
  summarise(lbs_per_person = sum(lbs_per_person)) %>%
  ggplot(aes(year, lbs_per_person, color = product)) +
  geom_line()

# use increase rate, we can see which product growth the fatest. 

milk_products_tidies %>%
  group_by(product = fct_lump(product, 6, w = lbs_per_person),
         year) %>%
  summarise(lbs_per_person = sum(lbs_per_person)) %>%
  spread(year, lbs_per_person) %>%
  mutate(increase_rate = (`2017` - `1975`) /`1975`) %>%
  select(product, increase_rate) %>%
  arrange(desc(increase_rate))

# 

milk_products_tidies %>%
  ggplot(aes(year, lbs_per_person)) +
  geom_line() +
  facet_wrap( ~ product, scales = "free") +
  expand_limits(y = 0)

milk_products_tidies %>%
  filter(year == max(year)) %>%
  mutate(product = fct_reorder(product, lbs_per_person, sum)) %>%
  ggplot(aes(product, lbs_per_person, fill = category)) +
  geom_col(show.legend = F) +
  coord_flip() +
  labs(x = "", y = "Pounds consumed per US person in 2017")

```

```{r}


milk_products_ts <- milk_products_tidies %>%
  mutate(year = as.Date("0001-01-01") + years(year - 1)) %>% 
  nest(-category, -product) %>%
  mutate(ts = map(data, tk_ts, start = 1975, freq = 1))


mlk_product_ets <- milk_products_ts %>%
  mutate(model = map(ts, ets))

mlk_product_ets %>%
  unnest(map(model, sw_glance))
  
milk_products_ts %>%
  crossing(model_name = c("auto.arima", "ets")) %>%
  mutate(model = map2(model_name, ts, ~ invoke(.x, list(.y))),
         forecast = map(model, forecast, h = 10)) %>%
  unnest(map(forecast, sw_sweep)) %>%
  ggplot(aes(index, lbs_per_person, color = model_name, lty = key)) +
  geom_line() +
  geom_ribbon(aes(ymin= lo.80, ymax = hi.80), alpha = .5) +
  facet_wrap( ~ product, scales = "free_y") +
  expand_limits(y = 0) +
  theme_tq() +
  scale_x_continuous(breaks = c(1980, 2000, 2020)) +
  scale_linetype_discrete(guide = F) +
  labs(x = "year",
       y = "Average US conumption (lbs per person)",
       subtitle = "Based on USDA data 1975-2017. Show 80% perdiction prediction interval",
       title = "Forecasted consumption of dairy proucts")


```


```{r}
cheese <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/clean_cheese.csv") 

cheese_tidied <- cheese %>%
  gather(type, lbs_per_person, -Year) %>%
  rename(year = Year) %>%
  mutate(type = str_to_title(type),
         type = fct_recode(type, "Total American Cheese" = "Total American Chese"))


cheese_tidied %>%
  ggplot(aes(year, lbs_per_person)) +
  geom_line() +
  facet_wrap( ~ type, scales = "free_y") +
  expand_limits(y = 0)


cheese_ts <- cheese_tidied %>%
  mutate(year = as.Date("0001-01-01") + years(year - 1)) %>%
  nest(-type) %>%
  mutate(ts = map(data, tk_ts, start = 1970, freq = 1))

cheese_ts %>%
  crossing(model_name = c("auto.arima", "ets")) %>%
  mutate(model = map2(model_name, ts, ~ invoke(.x, list(.y))),
         forecast = map(model, forecast, h = 10)) %>%
  unnest(map(forecast, sw_sweep)) %>%
  ggplot(aes(index, lbs_per_person, color = model_name, lty = key)) +
  geom_line() +
  geom_ribbon(aes(ymin= lo.80, ymax = hi.80), alpha = .5) +
  facet_wrap( ~ type, scales = "free_y") +
  expand_limits(y = 0) +
  theme_tq() +
  scale_x_continuous(breaks = c(1980, 2000, 2020)) +
  scale_linetype_discrete(guide = F) +
  labs(x = "year",
       y = "Average US conumption (lbs per person)",
       subtitle = "Based on USDA data 1975-2017. Show 80% perdiction prediction interval",
       title = "Forecasted consumption of dairy proucts")



```









