---
title: "Bike frequencies in seattle"
author: "Yifei Liu"
date: "4/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
detach("package:dplyr", unload=TRUE)
library(dplyr)
library(lubridate)
library(ggplot2)
theme_set(theme_minimal())
library(scales)
library(tidycensus)

```

```{r}
bike_traffic_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-02/bike_traffic.csv")

bike_traffic <- bike_traffic_raw %>%
  mutate(date = mdy_hms(date)) %>%
  filter(bike_count < 2000) %>%
  select(-ped_count)


```


```{r}

bike_traffic %>%
  ggplot(aes(date, fill = is.na(bike_count))) +
  geom_histogram() +
  facet_wrap(crossing ~ direction)



```

### When in the day do we see kikers?

```{r}
bike_traffic %>%
  group_by(crossing,
           hour = hour(date)) %>%
  summarize(bike_count = sum(bike_count)) %>%
  mutate(pct_bike = bike_count / sum(bike_count)) %>%
  ggplot(aes(hour, pct_bike, color = crossing)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = percent_format()) +
  scale_x_continuous(breaks = seq(0, 23, 2)) +
  labs(title = "when in the day do people bike through these Seattle crossings?",
       subtitle = "Based on crossing from 18/12/13 - 28/02/19",
       x = "Time of day (local time)",
       y = "% of bike crossings that happen in this hour")

```


```{r}
bike_by_time_window <- bike_traffic %>%
  mutate(hour = hour(date)) %>%
  mutate(time_window = case_when(
    between(hour, 7, 8) ~"Morning Commute",
    between(hour, 11, 15) ~ "Midday",
    between(hour, 16, 18) ~ "Evening Commute",
    T ~ "Night"
  )) %>%
  group_by(crossing, 
           time_window) %>%
  summarize(num_missing = sum(is.na(bike_count)),
            bike_count = sum(bike_count, na.rm = T)) %>%
  mutate(pct_bike = bike_count / sum(bike_count))
  
bike_by_time_window %>%
  select(- num_missing, - bike_count) %>%
  spread(time_window, pct_bike) %>%
  mutate(TotalCommute = `Evening Commute` + `Morning Commute`) %>%
  arrange(desc(TotalCommute))

bike_by_time_window %>%
  ggplot(aes(time_window, pct_bike)) +
  geom_col() +
  coord_flip() +
  facet_wrap( ~ crossing)

bike_by_time_window %>%
  group_by(crossing) %>%
  summarize(total_bikes = sum(bike_count),
            pct_commute = sum(bike_count[str_detect(time_window, "Commute")]) / total_bikes) %>%
  ggplot(aes(total_bikes, pct_commute)) +
  geom_point() +
  scale_x_log10()

```


```{r}
bike_traffic %>%
  group_by(crossing, 
           weekday = wday(date, label = T),
           hour = hour(date)) %>%
  summarize(total_bikes = sum(bike_count, na.rm = T)) %>%
  group_by(crossing) %>%
  mutate(pct_bike = total_bikes / sum(total_bikes)) %>%
  ggplot(aes(hour, pct_bike, color = weekday)) +
  geom_line(show.legend = F) +
  facet_grid(crossing ~ weekday) +
  scale_y_continuous(labels = percent_format()) +
  scale_color_manual(values = rainbow(7)) +
  labs(x = "Time of week",
       y = "% of bike crossing happening in this hour",
       title = "When in week do people bike",
       subtitle = "Based on crossing from 18/12/13 - 28/02/19")

```

```{r}
bike_traffic %>%
  filter(date < "2018-01-01") %>%
  group_by(month = fct_relevel(month.name[month(date)], month.name),
           crossing) %>%
  summarize(total_bikes = sum(bike_count, na.rm = T)) %>%
  mutate(pct_bikes = total_bikes / sum(total_bikes)) %>%
  ggplot(aes(month, pct_bikes, color = crossing, group = crossing)) +
  geom_line() +
  expand_limits(y = 0) +
  scale_y_continuous(labels = percent_format()) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(subtitle = "Based on 2014-2017 bike crossings",
       title = "What time of year do people bike?")

```
### what direction do people commute by bike?


```{r}
bike_by_direction_hour_crossing <- bike_traffic %>%
  filter(crossing != "MTS Trail",
         !wday(date, label = TRUE) %in% c("Sat", "Sun"),
         direction %in% c("North", "South")) %>%
  mutate(hour = hour(date)) %>%
  group_by(crossing, 
           direction,
           hour) %>%
  summarize(bike_count = sum(bike_count, na.rm = T)) %>%
  mutate(pct_bike = bike_count / sum(bike_count))

  
  
bike_by_direction_hour_crossing %>%
  group_by(crossing) %>%
  mutate(average_hour = sum((hour * pct_bike)[direction == "North"])) %>%
  ungroup() %>%
  mutate(crossing = fct_reorder(crossing, average_hour)) %>%
  ggplot(aes(hour, pct_bike, color = direction)) +
  geom_line(size = 1) +
  facet_grid(crossing~.) +
  scale_y_continuous(labels = percent_format()) +
  scale_x_continuous(breaks = seq(0, 23, 2)) +
  labs(title = "In which directions do people commute by bike?",
       subtitle = "Based on crossing at six Seattle Locations from 18/12/13 - 28/02/19",
       x = "Time of day (local time)",
       y = "% of bike crossings that happen in this Day",
       color = "Direction")


```








