---
title: "Untitled"
author: "Yifei Liu"
date: "11/21/2018"
output: html_document
---

```{r}
library(tidyverse)
library(widyr)
library(ggraph)
library(igraph)
library(ebbr)
theme_set(theme_minimal())
```


```{r, message=F}
thanksgiving_survey <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-11-20/thanksgiving_meals.csv") %>%
  mutate(family_income = fct_reorder(family_income, parse_number(family_income)))
```


almost everyone serves turkey as the main disk 


```{r}
thanksgiving_survey%>%
  dplyr::count(main_dish, main_prep, sort = T)

thanksgiving_survey %>%
  dplyr::count(gravy, sort = T)

x <- thanksgiving_survey %>%
  mutate(family_income = fct_reorder(family_income, parse_number(family_income)))

thanksgiving_survey %>%
  dplyr::count(family_income)

thanksgiving_survey %>%
  dplyr::filter(cranberry %in% c("Canned", "Homemade")) %>%
  group_by(family_income) %>%
  dplyr::summarize(homemade = mean(cranberry == "Homemade"),
            size = n()) %>%
  ggplot(aes(family_income, homemade, group = 1)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

thanksgiving_survey %>%
  dplyr::filter(cranberry %in% c("Canned", "Homemade")) %>%
  group_by(family_income) %>%
  dplyr::summarise(homemade = sum(cranberry == "Homemade"),
                   total = n(),
                   low = qbeta(0.025, 0.5 + homemade, total - homemade + .5),
                   high = qbeta(0.975, 0.5 + homemade, total - homemade + .5)) %>%
  ggplot(aes(x = family_income, y = homemade / total, group = 1)) +
  scale_y_continuous(labels = scales::percent_format()) +
  geom_line() +
  geom_ribbon(aes(ymin = low, ymax = high), alpha = .2) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = "Family income",
       y = "% serving homemade")



```

## Relationship with income


```{r}
thanksgiving_survey %>%
  group_by(family_income) %>%
  dplyr::summarise(celebrate = sum(celebrate == "Yes"),
                   total = n(),
                   low = qbeta(0.025, 0.5 + celebrate, total - celebrate + .5),
                   high = qbeta(0.975, 0.5 + celebrate, total - celebrate + .5)) %>%
  ggplot(aes(x = family_income, y = celebrate / total, group = 1)) +
  scale_y_continuous(labels = scales::percent_format()) +
  geom_line() +
  geom_ribbon(aes(ymin = low, ymax = high), alpha = .2) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = "Family income",
       y = "% Celebrate thanksgiving")


```

What are the most common pies, sides, and desserts?

```{r}
food_gathered <- thanksgiving_survey %>%
  select(id, starts_with("dessert"), starts_with("pie"), starts_with("side")) %>%
  select(-side15, -pie13, -dessert12) %>%
  gather(type, value, -id) %>%
  dplyr::filter(!is.na(value),
                !str_detect(value, "None|Other")) %>%
  mutate(type = str_remove(type, "\\d+"))

n_respondents <- n_distinct(food_gathered$id)

food_gathered %>%
  dplyr::count(type, value, sort = T) %>%
  mutate(value = fct_reorder(value, n)) %>%
  ggplot(aes(value, n / n_respondents, fill = type)) +
  geom_col(show.legend = F) +
  scale_y_continuous(labels = scales::percent_format()) +
  coord_flip() +
  facet_wrap(~type, ncol = 1, scales = "free_y") +
  labs(x = "",
       y = "% of respondents")
  

```


How do servings differ by income?

```{r}


food_gathered %>% 
  inner_join(thanksgiving_survey, by = "id") %>%
  mutate(age_numer = parse_number(age)) %>%
  group_by(value) %>%
  dplyr::summarise(average_age = mean(age_numer, na.rm = T),
                   total = n()) %>%
  arrange(desc(average_age)) %>%
  View()


food_by_region <- food_gathered %>% 
  inner_join(thanksgiving_survey, by = "id") %>%
  group_by(us_region) %>%
  mutate(respondents = n_distinct(id)) %>%
  dplyr::count(us_region, respondents,type, value) %>%
  ungroup() %>%
  mutate(percent = n / respondents)

food_by_region %>%
  dplyr::filter(value == "Apple") %>%
  arrange(desc(percent))
```



```{r}
food_gathered %>% 
  inner_join(thanksgiving_survey, by = "id") %>%
  dplyr::filter(!is.na(prayer)) %>%
  group_by(type, value) %>%
  dplyr::summarise(prayer = sum(prayer == "Yes"),
                   total = n()) %>%
  add_ebb_estimate(prayer, total) %>%
  arrange(desc(.fitted))

```


what side, pies and desserts are eaten together?

```{r}

food_cors <- food_gathered %>%
  pairwise_cor(value, id, sort = T) 

set.seed(2018)

food_types <- food_gathered %>%
  dplyr::count(value, type, sort = T)

food_cors %>%
  head(75) %>%
  graph_from_data_frame(vertices = food_types) %>%
  ggraph() +
  geom_edge_link() +
  geom_node_point(aes(color = type, size = n)) +
  geom_node_text(aes(label = name), vjust = 1, hjust  = 1, repel = T) +
  scale_size_continuous(labels = scales::percent_format()) +
  theme_void() +
  labs(title = "What foods get served together at Thanksgiving?",
       color = "",
       size = "% of respondents")

```



## summary

what I learn from this EDA

1. Intro to Emperical Bayesian, package = ebbr
2. Turn tidy data into wide data and do some correlation analysis package = widyr
































