---
title: "Tidy Tuesday - Analyzing incarceration data"
author: "Yifei Liu"
date: "1/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
theme_set(theme_minimal())
library(gganimate)
library(ggthemes)
library(tidycensus)

detach("package:dplyr", unload=TRUE)
library(dplyr)
```


```{r}
prison_summary <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-22/prison_summary.csv")

prison_population <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-22/prison_population.csv")

crime_original <- read_csv("https://raw.githubusercontent.com/vera-institute/incarceration_trends/master/incarceration_trends.csv")


prison_summary %>%
  filter(pop_category %in% c("White", "Black", "Latino", "Asian", "Native American"),
         year >= 1990) %>%
  ggplot(aes(year, rate_per_100000, color = urbanicity)) +
  geom_line() +
  facet_wrap(~ pop_category)



```


```{r}
prison_population %>% 
  count(region, sort = T)

prison_population_2015 <- prison_population %>%
  filter(year == 2015)

# filter out the state, 1. filter out county have no population data 2. filter out state which have no county have prison population 

non_missing_states <- prison_population_2015 %>%
  filter(!is.na(population)) %>%
  group_by(state) %>%
  filter(any(!is.na(prison_population)))


prison_population_2015 %>%
  group_by(state) %>%
  summarize(population = sum(population, na.rm = T),
            prison_population = sum(prison_population, na.rm = T))


# check na in prison_popultion, what kind of data are we missing

prison_population %>%
  group_by(year) %>%
  summarize(mean(is.na(prison_population)))

# check in 2015 how many state that have at least one county have prison population data

non_missing_states %>%
  ungroup() %>%
  summarize(mean(is.na(prison_population)))


# after filter prison population equal to zero, we can assume the NA is missing data

non_missing_states %>%
  ungroup() %>%
  filter(prison_population == 0)

# for instance, in North Dakota, we have 11.7% of population leave in a county, where there is no prison population. 

non_missing_states %>%
  summarize(total_pop_missing_prison = sum(population[is.na(prison_population)] / sum(population))) %>%
  arrange(desc(total_pop_missing_prison))


non_missing_states %>%
  group_by(population_category = cut(population, c(-1, 100, 1000, 10000, Inf))) %>%
  summarize(pct_missing = mean(is.na(prison_population)),
            observation = n())

# most small county we will have missing prison population data, but we have most prison population data in large county.

```

 We're dropping 22 state where we never have prison population data. We are looking at year 2015 (most recent with prison data), and we are dropping `r scales::percent(mean(is.na(population$population)))` of our observations where we don't have overall population data. 
 
```{r}
by_state <- non_missing_states %>%
  filter(!is.na(prison_population),
         pop_category == "Total") %>%
  group_by(state) %>%
  summarize_at(vars(population, prison_population), sum) %>%
  mutate(incarceration_rate = prison_population / population) %>%
  arrange(desc(incarceration_rate))

map_data("state") %>%
  tbl_df()

by_state %>%
  mutate(region = str_to_lower(state.name[match(state, state.abb)])) %>%
  right_join(map_data("state"),  by = "region") %>%
  ggplot(aes(long, lat, group = group, fill = incarceration_rate)) +
  geom_polygon() +
  theme_map() +
  coord_map()



# state population

vars <- load_variables(year = 2015, dataset = "acs1")
pop_2015 <- get_acs(geography = "state", variables = "B01003_001")


```

```{r}
map_data("county") %>%
  tbl_df()

county_overall_2015 <- prison_population_2015 %>%
  filter(pop_category == "Total") %>%
  mutate(region = str_to_lower(state.name[match(state, state.abb)]),
         subregion = str_remove(str_to_lower(county_name), " county|parish| city"),
         incarceration_rate = prison_population / population) 

county_overall_2015 %>%
  filter(incarceration_rate < .05) %>%
  right_join(map_data("county"), by = c("region", "subregion")) %>%
  ggplot(aes(long, lat, group = group, fill = incarceration_rate)) +
  geom_polygon() +
  theme_map() +
  coord_map() +
  scale_fill_gradient2(low = "blue", high = "red", midpoint = .01,
                        labels = percent_format())

# remove McPherson because it will below up the whole color scale

county_overall <- prison_population %>%
  filter(pop_category == "Total") %>%
  mutate(region = str_to_lower(state.name[match(state, state.abb)]),
         subregion = str_remove(str_to_lower(county_name), " county|parish| city"),
         incarceration_rate = prison_population / population) %>%
  filter(!is.na(incarceration_rate),
         county_name != "McPherson County") %>%
  right_join(map_data("county"), by = c("region", "subregion"))

```

Just Texas

```{r}

county_overall %>%
  filter(region == "texas") %>%
  ggplot(aes(long, lat, group = group, fill = incarceration_rate)) +
  geom_polygon() +
  theme_map() +
  coord_map() +
  transition_manual(year) +
  scale_fill_gradient2(low = "blue", high = "red", midpoint = .01,
                        labels = percent_format(),
                       limits = c(0, .04))



```


```{r}


by_state_year <- prison_population %>%
  filter(pop_category == "Total") %>%
  group_by(year, state) %>%
  summarize(missing_prison = mean(is.na(prison_population)),
            population = sum(population[!is.na(prison_population)], na.rm = T),
            prison_population = sum(prison_population, na.rm = T)) %>%
  ungroup() %>%
  mutate(incarceration_rate = prison_population / population)

by_state_year %>%
  filter(state %in% c("TX", "NY", "CA", "MA", "MS")) %>%
  filter(missing_prison < .1) %>%
  ggplot(aes(year, incarceration_rate, color = state)) +
  geom_line() +
  geom_point() +
  expand_limits(y = 0)  +
  scale_y_continuous(labels = percent_format())


```










