---
title: "analyzing_bird_collisions"
author: "Yifei Liu"
date: "5/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(skimr)
library(rsample)
library(lubridate)
theme_set(theme_minimal())
```

```{r}
bird_collisions <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-30/bird_collisions.csv")
mp_light <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-30/mp_light.csv")


bird_collisions <- bird_collisions %>%
  left_join(mp_light, by = "date") 

bird_collisions %>%
  ggplot(aes(date, fill = locality)) +
  geom_histogram()


```


```{r}

bird_collisions %>%
  gather(category, value, -date, - light_score) %>%
  count(category, value, light_score_missing = is.na(light_score)) %>%
  group_by(category) %>%
  top_n(16, n) %>%
  ungroup() %>%
  mutate(value = fct_reorder(value, n, sum),
         category = reorder(category, n, length)) %>%
  na.omit() %>%
  ggplot(aes(value, n, fill = light_score_missing)) +
  geom_col() +
  facet_wrap(~ category, scales = "free_y") +
  coord_flip() +
  labs(x = "# of collisions",
       y = "",
       fill = "light score missing", 
       title = "Category Breakdowns of collisions")

```

```{r}
bird_collisions %>%
  filter(!is.na(light_score)) %>%
  count(date, locality) %>%
  ggplot(aes(n, color = locality)) +
  geom_density() +
  scale_x_log10() +
  labs(x = "# of collisions per night")

geom_mean <- function(x) {
  exp(mean(log(x + 1)) - 1)
}



bird_collisions %>%
  filter(!is.na(light_score)) %>%
  distinct(date, light_score) %>%
  ggplot(aes(light_score)) +
  geom_histogram()

by_day_map <- bird_collisions %>%
  filter(!is.na(light_score)) %>%
  group_by(date, locality) %>%
  summarize(collisions = n()) %>%
  ungroup() %>%
  complete(date, locality, fill = list(collisions = 0)) %>%
  right_join(mp_light %>% crossing(locality = c("CHI", "MP")), by = c("date", "locality")) %>%
  filter(date < "2016-11-13") %>%
  # the reason why we choose this date because we don't know whether the collision data after this day have been collected or not. you can use bird_collisions %>% filter(locality == "MP") %>% summarize(min(date), max(date)) and by_day_map %>% filter(collisions == 0) %>% summarize(min(date), max(date)) to check. 
  replace_na(list(collisions = 0)) %>%
  ungroup() %>%
  mutate(locality = ifelse(locality == "CHI", "Great Chicago", "McCormick place"))
  

by_day_map %>%
  group_by(light_score) %>%
  summarize(avg_collisions = exp(mean(log(collisions + 1)) -1),
            nights = n()) %>%
  ggplot(aes(light_score, avg_collisions)) +
  geom_line() +
  expand_limits(y = 0) +
  labs(y = "Geometric mean of number of collisions in a night",
       x = "light score at mcCormic Place (higher means more lights on",
       title = "Brigher lights at mcCormick place correlate with more bird collisions")

# see chart like this, David want to add confidence interval, use bootstrap method. 

```



```{r}


bootstrap_cis <- by_day_map %>%
  bootstraps(times = 100) %>%
  unnest(map(splits, as.data.frame)) %>%
  group_by(light_score, locality, id) %>%
  summarize(avg_collisions = geom_mean(collisions)) %>%
  summarize(bootstrap_low = quantile(avg_collisions, 0.025),
            bootstrap_high = quantile(avg_collisions, .975))
            

by_day_map %>%
  group_by(light_score, locality) %>%
  summarize(avg_collisions = geom_mean( collisions),
            nights = n()) %>%
  ggplot(aes(light_score, color = locality)) +
  geom_line(aes(y = avg_collisions)) +
  geom_ribbon(aes(ymin = bootstrap_low, ymax = bootstrap_high), alpha = 0.25, data = bootstrap_cis) +
  expand_limits(y = 0) +
  labs(y = "Geometric mean of number of collisions in a night",
       x = "light score at mcCormic Place (higher means more lights on)",
       title = "Bright relationship with different city area",
       caption = "Brigher lights at McCormick place correlate with more bird collisions \n but not with collision with Chicago overall",
       subtitle = "Riboon show 95% bootstrapped percentile confidence intervl") 


```


### Look at confounders

```{r}
bird_collisions %>%
  filter(date > "2005-01-01") %>%
  count(month = month(date, label = TRUE),
        locality) %>%
  ggplot(aes(month, n, color = locality, group = locality)) +
  geom_line()


```
Here is where David analysis end, but there are still plenty analysis could be explore further. Such as which genue, species have the highest number, seasonal pattern, use different time series model to forecast. etc. 

### let's look at different speices. 

let take a looke whcih 
ps: remind me the dolphain analysis


```{r}
bird_collisions

```













