---
title: "Analyze Pet names in Seattle"
author: "Yifei Liu"
date: "3/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(scales)
theme_set(theme_minimal())
library(dplyr, warn.conflicts = FALSE)
```


```{r}
seattle_pets <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-26/seattle_pets.csv") %>%
  mutate(license_issue_date = mdy(license_issue_date)) %>%
  rename(animal_name = animals_name)
```

EDA
```{r}
seattle_pets %>%
  mutate(license_issue_date = mdy(license_issue_date)) %>%
  ggplot(aes(license_issue_date)) +
  geom_histogram()

seattle_pets %>%
  filter(license_issue_date >= "2016-12-31") %>%
  count(primary_breed, species, sort = T) %>%
  filter(species %in% c("Cat", "Dog")) %>%
  mutate(percent = n / sum(n)) %>%
  group_by(species) %>%
  top_n(10, percent) %>%
  ungroup() %>%
  mutate(primary_breed = fct_reorder(primary_breed, percent)) %>%
  ggplot(aes(primary_breed, percent)) +
  geom_col(aes(fill = species), show.legend = F) +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_manual(values = c("darkgreen", "midnightblue")) +
  facet_wrap(~ species, scales = "free_y", ncol = 1) +
  coord_flip() +
  labs(x = "", y = "% of this species",
       title = "Most common cat and dog breeds",
       subtitle = "Of licensed pets in Seattle 2017 - 2018") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```



```{r}

dogs <- seattle_pets %>%
  filter(species == "Dog")
  
total_dogs <- nrow(dogs)

name_count <- dogs %>%
  group_by(animal_name) %>%
  summarize(name_total = n()) %>%
  filter(name_total >= 100)

breed_counts <- dogs %>%
  group_by(primary_breed) %>%
  summarize(breed_total = n()) %>%
  filter(breed_total >=200)

name_breed_counts <- dogs %>%
  count(primary_breed, animal_name) %>%
  complete(primary_breed, animal_name, fill = list(n = 0)) %>%
  inner_join(name_count, by = "animal_name") %>%
  inner_join(breed_counts, by = "primary_breed") 

# one side hypergeometric p-value

hypergeom_test <- name_breed_counts %>%
  mutate(percent_of_breed = n / breed_total,
         percent_overall = name_total / total_dogs) %>%
  mutate(overrepresented_ratio = percent_of_breed / percent_overall) %>%
  arrange(desc(overrepresented_ratio)) %>%
  mutate(hypergeom_p_value = 1 - phyper(n, name_total, total_dogs - name_total, breed_total),
         home_p_value = p.adjust(hypergeom_p_value),
         fdr = p.adjust(hypergeom_p_value, method = "fdr"))

hypergeom_test %>%
  filter(fdr <  0.05)
  
  
hypergeom_test %>%
  ggplot(aes(hypergeom_p)) +
  geom_histogram(binwidth = 0.05) +
  labs(x = "One-sided hypergeometric p-values for overrepresented name")
```
use fdr method result, we conclude that this six name overrepresent in this primary_breed. 



```{r}
crossing(name_total = c(100, 200, 300),
         breed_total = seq(200, 1000, 25)) %>%
  mutate(max_p_valuie = 1 - phyper(0, name_total, total_dogs - name_total, breed_total)) %>%
  ggplot(aes(breed_total, max_p_valuie, color = factor(name_total))) +
  geom_line() +
  labs(x = "Total # of dogs in breed",
       y = "Minimum one-sided p-value",
       color = "# of dogs with name")
```

```{r}
hypergeom_test %>%
  filter(fdr <= 0.5) %>%
  transmute(`Breed` = primary_breed,
         `Name` = animal_name,
         `# of dogs with name` = n,
         `% of breed` = percent(percent_of_breed),
         `% overall` = percent(percent_overall),
         `FDR-adjusted p-value` = fdr) %>%
  knitr::kable()
```



















