---
title: "Pizza Party"
author: "Yifei Liu"
date: "10/2/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(skimr)
library(leaflet)
library(broom)
theme_set(theme_minimal())

pizza_jared <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_jared.csv")

pizza_barstool <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_barstool.csv")

pizza_datafiniti <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_datafiniti.csv")


```


# [David Robinson screen recording](https://www.youtube.com/watch?v=Mkac8DHScps)


```{r}
answer_order <- c("Never Again", "Poor", "Average", "Good", "Excellent")

by_place_answer <- pizza_jared %>%
  mutate(time = as.POSIXct(time, origin = "1970-01-01"),
         date = as.Date(time),
         answer = fct_relevel(answer, answer_order)) %>%
  group_by(place, answer) %>%
  summarize(votes = sum(votes)) %>%
  mutate(total = sum(votes)) %>%
  mutate(percent = votes / total,
         answer_integer = as.integer(answer),
         average = sum(answer_integer * percent)) %>%
  ungroup()

by_place <- by_place_answer %>%
  distinct(place, total, average)
```


```{r}

# Need review

by_place_answer %>%
  # New tricks to filter top observations, compare with alternative filter(total >= n)
  filter(as.integer(fct_reorder(place, total, .desc = T)) <= 16,
         answer != "Fair") %>%
  mutate(place = glue::glue(" { place } ({ total })"), 
         place = fct_reorder(place, average)) %>%
  ggplot(aes(answer, percent)) +
  # I try to use alpha, transparency, as alternative to show total voters, I think this method is more straightford.  
  geom_col(fill = "red", aes(alpha = total / 50), show.legend = F) +
  facet_wrap( ~ place) +
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = "",
       y = "% of respondents",
       title = "Most popular pizza place in open state map",
       subtitle = "Only 16 pizza places with the most respondents",
       caption = "Data source: Jared Lander")


```


Do statistical test shwo confidence bound

use t-test

```{r}

# THIS TRICKS DOESN'T WORK,  try to add weight to individual ratings
# tidy(lm(c(1, 2, 3, 4, 5) ~ 1, weights = c(1, 3, 10, 20, 15)), conf.int = T)

# Need Review
t_test_repeated <- function(x, frequency) {
  tidy(t.test(rep(x, frequency)))
}

t_test_repeated(c(1, 2, 3, 4, 5), c(100, 300, 100, 200, 150))

by_place_answer %>%
  filter(total >= 3) %>%
  group_by(place, total) %>%
  summarize(t_test_result = list(t_test_repeated(answer_integer, votes))) %>%
  ungroup() %>%
  unnest(t_test_result) %>%
  select(place, total, average = estimate, low = conf.low, high = conf.high) %>%
  mutate(place = glue::glue(" { place } ({ total })"),
         place = fct_reorder(place, average)) %>%
  top_n(16, total) %>%
  ggplot(aes(average, place)) +
  geom_point(aes(size = total)) +
  geom_errorbarh(aes(xmin = low, xmax = high)) +
  labs(x = "Average score (1 - 5 Likert scale)",
       y = "",
       title = "Most popular pizza place in open state map",
       size = "# of voters") +
  theme(legend.position = "bottom") 

```




```{r}

pizza_barstool %>%
  filter(review_stats_all_count >= 50) %>%
  mutate(name = fct_reorder(name, review_stats_all_average_score)) %>%
  ggplot(aes(review_stats_all_average_score, name, size = review_stats_all_count)) +
  geom_point() +
  labs(size = "# of reviews",
       x = "Average rating",
       title = "Barstool Sports ratings of pizza places",
       y = "",
       subtitle = "Only places with at least 50 reviews")


```


```{r}
pizza_barstool %>%
  filter(review_stats_all_count >= 20) %>%
  mutate(city = fct_lump(city, 3)) %>%
  add_count(city) %>%
  mutate(city = glue::glue("{city}  ({ n })"),
         city = fct_reorder(city,review_stats_all_average_score, median, .desc = T)) %>%
  ggplot(aes(city, review_stats_all_average_score)) +
  geom_boxplot() +
  labs(subtitle = "Only pizza places with at least 20 reivews",
       title = "Do pizza ratings differ across cities?")



```


```{r}

pizza_cleaned <- pizza_barstool %>%
  select(place = name,
         price_level,
         contains("review")) %>%
  rename_all(~ str_remove(., "review_stats_")) %>%
  select(-contains("provider")) 

pizza_cleaned %>%
  filter(critic_count > 0) %>%
  ggplot(aes(critic_average_score, dave_average_score)) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_abline(color = "red") +
  labs(title = "Does Barstool Sports' Dave agree with the critics?",
       x = "Critic average score",
       y = "Dave Score")



```



```{r}
pizza_cleaned %>%
  filter(community_count >= 20) %>%
  ggplot(aes(community_average_score, dave_average_score)) +
  geom_point(aes(size = community_count)) +
  geom_abline(color = "red") +
  geom_smooth(method = "lm") +
  labs(size = "# of community reviews",
       x = "Community score",
       y = "Dave score") +
  theme(legend.position = "bottom") 


```

# My own analysis

pizza price range in different state

```{r}


pizza_datafiniti %>%
  group_by(province) %>%
  filter(n() > 250) %>%
  ungroup() %>%
  mutate(price = (price_range_min + price_range_max) / 2) %>%
  ggplot(aes(province, price)) +
  geom_violin()

```


 use leaflet put these on a map
 
```{r}

leaflet(pizza_datafiniti) %>%
  addTiles() %>%
  addCircles(lng = ~ longitude, lat = ~ latitude, weight = 1,
             radius = ~sqrt(price_range_max), popup = ~glue::glue("{ name } 
                                                                  { categories }"))


```











