---
title: "Tidy Tuesday - Tidying and analyzing US phds in R"
author: "Yifei Liu"
date: "2/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
detach("package:dplyr", unload=TRUE)
library(dplyr)
library(ggplot2)
library(tidyxl)
library(unpivotr)
theme_set(theme_minimal())


```





```{r}

# Major field of study

files <- dir(path = "/Users/yifeiliu/Documents/R/data/EDA/tidytuesday/data_tables", pattern = ".xlsx")

files_name <- paste("/Users/yifeiliu/Documents/R/data/EDA/tidytuesday/data_tables/",files, sep = "")

# major field general
cells <- xlsx_cells(files_name[12])
formats <- xlsx_formats(files_name[12])

indent <- formats$local$alignment$indent

major_fields <- cells %>% 
  filter(row >= 4L) %>%
  behead_if(indent[local_format_id] == 0, direction = "WNW", name = "field1") %>%
  behead_if(indent[local_format_id] == 1, direction = "WNW", name = "field2") %>%
  behead_if(indent[local_format_id] == 2, direction = "WNW", name = "field3") %>%
  behead("NNW", "year") %>%
  behead("N", "metric") %>%
  select(numeric, field2, field3, year, metric, value = numeric)

# specific field

cells <- xlsx_cells(files_name[13])
formats <- xlsx_formats(files_name[13])

indent <- formats$local$alignment$indent

fine_major <- cells %>%
  filter(row >= 4L) %>%
  behead_if(indent[local_format_id] == 1, direction = "WNW", name = "field1") %>%
  behead_if(indent[local_format_id] == 2, direction = "WNW", name = "field2") %>%
  behead_if(indent[local_format_id] == 3, direction = "WNW", name = "field3") %>%
  behead("N", "year") %>%
  select(numeric, field1, field2, field3, year, value = numeric) %>%
  mutate(year = as.numeric(year))


# by gender

cells <- xlsx_cells(files_name[15])
formats <- xlsx_formats(files_name[15])

indent <- formats$local$alignment$indent

fields_sex <- cells %>%
  filter(row >= 4L) %>%
  behead_if(indent[local_format_id] == 1, direction = "WNW", name = "field2") %>%
  behead_if(indent[local_format_id] == 2, direction = "WNW", name = "field3") %>%
  behead_if(indent[local_format_id] == 3, direction = "WNW", name = "field4") %>%
  behead("NNW", "year") %>%
  select(numeric , field2, field3, field4, year, value = numeric) 




cells <- xlsx_cells(files_name[22])
formats <- xlsx_formats(files_name[22])

indent <- formats$local$alignment$indent

x <- cells %>% 
  filter(row >= 4L) %>%
  behead_if(indent[local_format_id] == 0, direction = "WNW", name = "field1") %>%
  behead_if(indent[local_format_id] == 1, direction = "WNW", name = "field2") %>%
  behead_if(indent[local_format_id] == 2, direction = "WNW", name = "field3") %>%
  behead_if(indent[local_format_id] == 3, direction = "WNW", name = "field4") %>%
  behead_if(indent[local_format_id] == 4, direction = "WNW", name = "field5") %>%
  behead("NNW", "head1") %>%
  behead("NNW", "head2") %>%
  behead("NNW", "head3") %>%
  select(row, col, starts_with("field"), starts_with("head"), value = numeric)
  

x %>%
  filter(col == 3)
  
```



```{r}



major_fields %>%
  filter(field2 %in% sample(unique(field2, 6)),
         metric == "Number") %>%
  group_by(year, field2) %>% 
  summarize(sum = sum(value)) %>%
  ggplot(aes(year, sum, color = field2)) +
  geom_line() +
  expand_limits(y = 0)

fine_major %>%
  filter(!is.na(value)) %>%
  filter(field3 %in% sample(unique(field3), 6)) %>%
  ggplot(aes(year, value, color = field3)) +
  geom_line() +
  expand_limits(y = 0)

  

fields_sex %>%
  filter((!year %in% c("Sex and major field of study", "% change 2008–17")),
         !is.na(field2)) %>%
  mutate(year = as.numeric(year),
         sex = case_when(
           field2 == "Male" ~ "Male",
           field2 == "Female" ~ "Female",
           TRUE ~ "All"
         ))


```














