---
title: "United_nations_comtrade_API"
author: "Yifei Liu"
date: "3/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(comtradr)
library(tidyverse)
theme_set(theme_minimal())
```


```{r}
ex_1 <- ct_search(reporters = "USA",
                  partners = "Mexico",
                  trade_direction = "imports")

# all shipments related to cars between US and all other countries, between 2015 - 2018
# perform "vehicle" query

vehicle_codes <- ct_commodity_lookup("vehicle",
                                     return_code = T,
                                     return_char = T)

# Make API call

chunk <- function(x, n) split(x, sort(rank(x) %% n))
vehicle_codes <- chunk(vehicle_codes, 6)



map(vehicle_codes,function(x)  ct_search(reporters = "USA",
                  partners = "Mexico",
                  trade_direction = "import",
                  start_date = 2015,
                  end_date = 2019,
                  commod_codes = x))


```



plastic waste import

```{r}
ex_2 <- ct_search(reporters = "world",
                  partners = "All",
                  trade_direction = "import",
                  freq = "annual",
                  start_date = 2010,
                  end_date = 2010,
                  commod_codes = "3915")


ex_2 %>%
  arrange(desc(netweight_kg))

```





