---
title: "World Bank API"
author: "Yifei Liu"
date: "11/10/2018"
output: html_document
---

# World Bank API dataset

https://github.com/mrpsonglao/data360r

https://blogs.worldbank.org/opendata/introducing-data360r-data-power-r
https://tcdata360.worldbank.org/tools/data360r


```{r}
library(tidyverse)
detach("package:dplyr", unload=TRUE)
library(dplyr)
library(scales)
library(wbstats)
theme_set(theme_minimal())
library(data360r)
```


```{r}


df <- get_metadata360(site='tc', metadata_type = 'indicators')


data_53 <- get_data360(dataset_id = 53) 

global_competitiveness_index <- data_53 %>%
  tbl_df() %>%
  setNames(c("country_iso3", "country", "indicator", "subindicator_type",
           '2007', '2008', '2009','2010' , '2011', '2012', '2013',
           '2014', "2015", '2016', '2017', "2018", "dataset_id")) %>% 
  select(-"2018") %>%
  filter(str_detect(indicator, " pillar"))
  

```


## let's take a look at institutions
```{r}

world <- map_data("world") %>%
  dplyr::filter(region != "Antarctica") %>%
  tbl_df()

institutions <- global_competitiveness_index %>%
  filter(str_detect(indicator, "Institutions"),
                subindicator_type == "Value")

institutions_processed <- institutions %>%
  distinct(country, indicator, .keep_all = T) %>%
  inner_join(maps::iso3166 %>%
               select(a3, mapname) %>%
                mutate(mapname = str_remove(mapname, "\\(.*")), 
             by = c(country_iso3 = "a3"))


institutions_processed <- institutions_processed %>%
  gather("2007", "2008", "2008", "2009", "2010", "2011", "2012", "2013",
         "2014", "2015", "2016", "2017", key = "year", value = "score")



institutions_map <- world %>%
  inner_join(institutions_processed, by = c(region = "mapname"))


institutions_map %>%
  ggplot(aes(long, lat, group = group, fill = score)) +
  geom_polygon() +
  scale_fill_gradient2(low = "blue", high = "red", midpoint = 4) +
  theme_void() +
  labs(title = "Global Competitiveness Index Institutions in :Year: {frame_time}",
       fill = "Institution Score")
  




```

### Governmant efficiency

```{r}
gov_eff <- get_data360(site = "tc", indicator_id = c(388, ))

gov_eff %>%
  filter(`Country Name` == "France")

```


### Visualize GDP growth 

```{r}
gdp_vars <- wbsearch(pattern = "GDP growth")

gdp_grwoth <- wb(indicator = "NY.GDP.MKTP.KD.ZG", startdate = 2000, enddate = 2017)

oecd_gdp <- gdp_grwoth %>%
  filter(iso3c %in% c("CAN", "DEU", "FRA", "GBR", "ITA", "JPN", "USA")) %>%
  mutate(date = as.numeric(date),
         value = value / 100)

oecd_gdp %>%
  ggplot(aes(date, value)) +
  facet_wrap( ~ country) +
  geom_line() +
  geom_hline(yintercept = 0, col = "grey") +
  geom_vline(xintercept = 2007, lty = "dashed") +
  labs(x = "", y = "",
       title = "Quarterly GDP growth before and after 2007 Financial Crisis.",
       subtitle = "Source: World Bank") +
  scale_y_continuous(labels = percent_format()) +
  theme(panel.grid = element_blank(),
        strip.text.x = element_text(size = 10, face = "bold"))
  

oecd_summary <- oecd_gdp %>%
  group_by(date) %>%
  summarize(gdp_low = min(value),
            gdp_max = max(value),
            gpd_mean = mean(value))


ggplot(oecd_summary) +
  geom_line(size = 1, aes(date, gpd_mean)) +
  geom_ribbon(aes(x = date, ymin = gdp_low, ymax = gdp_max),alpha = 0.2) +
  geom_line(data = oecd_gdp, aes(date, value, color = country), alpha = 0.2) +
  geom_hline(yintercept = 0, col = "grey") +
  scale_y_continuous(labels = percent_format()) +
  geom_vline(xintercept = 2007, lty = 2) +
  annotate(geom = "text", x = 2006, y = -0.02, label = "Global Financial Crisis", angle = 90) +
  labs(x = "", y = "", 
       title = "GDP grwoth of G7 in Relation to Financial Crisis",
       subtitle = "Data: Word Bank",
       color = "") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, face = "italic"))


```


### Finding available data with wb_cachelist


```{r}
str(wb_cachelist, max.level = 1)

wb_cachelist$indicators %>%
  count(source)

```








